namespace BedrockProtocol.Packets.Enums
{
    public enum EntityFlag : long
    {
        OnFire = 0,
        Sneaking = 1,
        Riding = 2,
        Sprinting = 3,
        Action = 4,
        Invisible = 5,
        Tempted = 6,
        InLove = 7,
        Saddled = 8,
        Powered = 9,
        Ignited = 10,
        Baby = 11,
        Converting = 12,
        ShowingName = 13,
        AlwaysShowName = 14,
        NoAi = 15,
        Silent = 16,
        WallClimbing = 17,
        Resting = 18,
        Sitting = 19,
        Angry = 20,
        Interested = 21,
        Charged = 22,
        Tamed = 23,
        Orphaned = 24,
        Leashed = 25,
        Sheared = 26,
        Gliding = 27,
        Elder = 28,
        Moving = 29,
        Breathing = 30,
        Chested = 31,
        Stunned = 32,
        HasCollision = 33,
        AffectedByGravity = 34,
        FireImmune = 35,
        Dancing = 36,
        Idling = 37,
        StylizedExhibit = 38,
        Blinking = 39,
        Treading = 40,
        HasLeashHolder = 41,
        Stung = 42,
        CanSwim = 43,
        HadDishonorableDeath = 44,
        InAscendableBlock = 45,
        OnScaffolding = 46,
        InOverworld = 47,
        InNether = 48,
        InTheEnd = 49,
        InMountRange = 50,
        CanFly = 51,
        CanClimb = 52,
        CanGoDown = 53,
        CanGoUp = 54,
        CanOpenDoors = 55,
        CanOpenIronDoors = 56,
        CanPickUpItems = 57,
        CanWalkInWater = 58,
        CanBeScared = 59,
        CanFlyOnScaffolding = 60,
        SprintingWithParticles = 61
    }
}
